export const colors = [
  "pink",
  "rose",
  "orange",
  "green",
  "mint",
  "sky",
  "cyan",
  "lavender",
  "indigo",
  "olive",
  "grape",
  "winterNight",
  "beige",
  "cherry",
  "teal",
  "plum",
];
export const icons = [
  "🧶",
  "🧣",
  "👚",
  "🤍",
  "🍰",
  "🍵",
  "✨",
  "❄️",
  "🦊",
  "🐺",
  "🐈",
  "🦉",
  "🪶",
  "🌲",
  "🌊",
  "⚡",
  "🚗",
  "🍇",
  "🍊",
  "🍒",
  "🍓",
  "🌸",
  "🪄",
  "🎵",
  "🎞️",
  "🧩",
  "🖼️",
  "📖",
  "🍂",
  "☀️",
  "🌙",
];

export const names = [
  "River",
  "Lake",
  "Sea",
  "Ocean",
  "Forest",
  "Winter",
  "Spring",
  "Summer",
  "Autumn",
  "Sun",
  "Moon",
];

// TODO: add more presets
export const presets = [
  { name: "River", theme: "green", icon: "🌲" },
  { name: "Lake", theme: "green", icon: "🌲" },
  { name: "Sea", theme: "cyan", icon: "🌊" },
  { name: "Ocean", theme: "cyan", icon: "🌊" },
  { name: "Forest", theme: "green", icon: "🌲" },
  { name: "Winter", theme: "sky", icon: "❄️" },
  { name: "Spring", theme: "green", icon: "🌸" },
  { name: "Summer", theme: "cherry", icon: "🍓" },
  // { name: "Summer", theme: "cherry", icon: ["🍓", "🍒", "☀️"] },
  { name: "Autumn", theme: "orange", icon: "🍂" },
  { name: "Sun", theme: "orange", icon: "☀️" },
  { name: "Moon", theme: "winterNight", icon: "🌙" },
];
